# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roboflow Starter Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roboflow Starter Project
   pod 'Roboflow'

  target 'Roboflow Starter ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Roboflow Starter ProjectUITests' do
    # Pods for testing
  end

end
